src/PullRequestsViewer.WebApp/Controllers/RepositoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PullRequestsViewer.Domain.Interfaces;
using PullRequestsViewer.WebApp.Extensions;
using PullRequestsViewer.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PullRequestsViewer.WebApp.Controllers
{
    public class RepositoryController : Controller
    {
        private readonly IOrganisationRepository _organisationRepository;

        public readonly IRepositoryRepository _repositoryRepository;
        private readonly IRepositoryPersistence _repositoryPersistence;
        private readonly ICredentialsRepository _credentialsRepository;
        private readonly ILogger<RepositoryController> _logger;

        public RepositoryController(IOrganisationRepository organisationRepository,
            IRepositoryRepository repositoryRepository,
            IRepositoryPersistence repositoryPersistence,
            ICredentialsRepository credentialsRepository,
            ILogger<RepositoryController> logger)
        {
            _organisationRepository = organisationRepository;
            _repositoryRepository = repositoryRepository;
            _repositoryPersistence = repositoryPersistence;
            _credentialsRepository = credentialsRepository;
            _logger = logger;
        }

        [ActionName("Index")]
        public async Task<IActionResult> IndexAsync()
        {
            try
            {
                // TODO make this middleware for relevant actions.
                if (!_credentialsRepository.IsUserSetted())
                    return RedirectToAction("Index", "Home");

                var organisationModels = new List<OrganisationModel>();

                // TODO rename the class to some that cover this use case.
                organisationModels.Add(new OrganisationModel
                {
                    Name = _credentialsRepository.User.Username,
                    Repositories = (await _repositoryRepository.GetAllForCurrentAsync()).ConvertToModel()
                });

                var organisations = await _organisationRepository.GetOrganisationsAsync();

                foreach (var organisation in organisations)
                {
                    var organisationModel = new OrganisationModel
                    {
                        Name = organisation.Name,
                        Repositories = (await _repositoryRepository.GetAllAsync(organisation)).ConvertToModel()
                    };
                    organisationModels.Add(organisationModel);
                }

                return View(new OrganisationRepositoriesViewModel(organisationModels,
                    await _repositoryPersistence.GetAllAsync()));
            }
            catch (Exception exception)
            {
                _logger.LogError(exception, exception.Message);
                throw;
            }
        }

        [HttpPost]
        [ActionName("Index")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> IndexAsync(
            OrganisationRepositoriesViewModel organisationRepositoriesViewModel)
        {
            try
            {
                await _repositoryPersistence.SaveAsync(
                    organisationRepositoriesViewModel.ConvertToDomainRepositories());
                return RedirectToAction("Index", "Home");
            }
            catch (Exception exception)
            {
                _logger.LogError(exception, exception.Message);
                throw;
            }
        }
    }
}

src/PullRequestsViewer.WebApp/Views/Repository/Index.cshtml
@model OrganisationRepositoriesViewModel
<div class="page-header">
    <h1>Repositories. <small>Your repositories.</small></h1>
</div>

@using (Html.BeginForm("Index", "Repository", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>

    @for (var i = 0; i < Model.Organisations.Count; i++)
    {
        <h3>@Model.Organisations[i].Name</h3>
        <div class="table-striped">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th></th>
                        <th>@Html.LabelFor(x => x.Organisations.First().Repositories.First().Name)</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var j = 0; j < Model.Organisations[i].Repositories.Count; j++)
                    {
                        <tr>
                            <td>
                                @Html.CheckBox("organisationRepositoriesViewModel.Organisations[" + i + "].Repositories[" + j + "].Selected",
                                    Model.Organisations.ElementAt(i).Repositories.ElementAt(j).Selected,
                                    null)
                            </td>
                            <td>
                                @Html.Hidden("organisationRepositoriesViewModel.Organisations[" + i + "].Repositories[" + j + "].Name",
                                    Model.Organisations.ElementAt(i).Repositories.ElementAt(j).Name)
                                @Html.Hidden("organisationRepositoriesViewModel.Organisations[" + i + "].Repositories[" + j + "].OwnerLogin",
                                    Model.Organisations.ElementAt(i).Repositories.ElementAt(j).OwnerLogin)
                                @Html.DisplayFor(x => x.Organisations.ElementAt(i).Repositories.ElementAt(j).Name)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }

    <button type="submit" class="btn btn-primary">Save</button>
}